version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s:%(levelname)s:%(name)s: %(message)s'
  error:
    format: '%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: ./tmp/debug.log
    maxBytes: 52428800 # 50MB
    backupCount: 5
    encoding: utf8
    mode: 'w'

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: ./tmp/info.log
    maxBytes: 52428800 # 50MB
    backupCount: 5
    encoding: utf8
    mode: 'w'

  warn_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: WARN
    formatter: standard
    filename: ./tmp/warn.log
    maxBytes: 52428800 # 50MB
    backupCount: 5
    encoding: utf8
    mode: 'w'

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: error
    filename: ./tmp/error.log
    maxBytes: 52428800 #50MB
    backupCount: 2
    encoding: utf8
    mode: 'w'

  critical_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: CRITICAL
    formatter: error
    filename: ./tmp/critical.log
    maxBytes: 52428800 # 50MB
    backupCount: 2
    encoding: utf8
    mode: 'w'

loggers:
  root:
    level: DEBUG
    handlers: [info_file_handler, error_file_handler, debug_file_handler, critical_file_handler, warn_file_handler]
    propogate: true
    
  aperture:
    level: DEBUG
    handlers: [info_file_handler, error_file_handler, debug_file_handler, critical_file_handler, warn_file_handler]
    propogate: true

  discord:
    level: DEBUG
    handlers: [info_file_handler, error_file_handler, debug_file_handler, critical_file_handler, warn_file_handler]
    propogate: true

  apscheduler:
    level: DEBUG
    handlers: [info_file_handler, error_file_handler, debug_file_handler, critical_file_handler, warn_file_handler]
    propogate: true